/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLifeBalanceDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type LifeBalanceDto, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/analytics/life-balance
 */
export interface LifeBalanceRequestBuilder extends BaseRequestBuilder<LifeBalanceRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LifeBalanceDto>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LifeBalanceDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LifeBalanceRequestBuilderUriTemplate = "{+baseurl}/api/analytics/life-balance";
/**
 * Metadata for all the requests in the request builder.
 */
export const LifeBalanceRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LifeBalanceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLifeBalanceDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
