/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CompleteRequestBuilderRequestsMetadata, type CompleteRequestBuilder } from './complete/index.js';
// @ts-ignore
import { type UndoRequestBuilder, UndoRequestBuilderRequestsMetadata } from './undo/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/occurrences/{id}
 */
export interface OccurrencesItemRequestBuilder extends BaseRequestBuilder<OccurrencesItemRequestBuilder> {
    /**
     * The complete property
     */
    get complete(): CompleteRequestBuilder;
    /**
     * The undo property
     */
    get undo(): UndoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OccurrencesItemRequestBuilderUriTemplate = "{+baseurl}/api/occurrences/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OccurrencesItemRequestBuilderNavigationMetadata: Record<Exclude<keyof OccurrencesItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    complete: {
        requestsMetadata: CompleteRequestBuilderRequestsMetadata,
    },
    undo: {
        requestsMetadata: UndoRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
