/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type DateOnly, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ApiOperationResult extends ApiError, Parsable {
    /**
     * The errors property
     */
    errors?: ApiOperationResult_errors | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
}
export interface ApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface ConfirmEmailCommand extends Parsable {
    /**
     * The confirmationCode property
     */
    confirmationCode?: string | null;
    /**
     * The userId property
     */
    userId?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApiOperationResult_errors}
 */
// @ts-ignore
export function createApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApiOperationResult}
 */
// @ts-ignore
export function createApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfirmEmailCommand}
 */
// @ts-ignore
export function createConfirmEmailCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfirmEmailCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateTaskCommand}
 */
// @ts-ignore
export function createCreateTaskCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateTaskCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponseApiOperationResult_errors}
 */
// @ts-ignore
export function createLoginResponseApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponseApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponseApiOperationResult}
 */
// @ts-ignore
export function createLoginResponseApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponseApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponse}
 */
// @ts-ignore
export function createLoginResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginUserCommand}
 */
// @ts-ignore
export function createLoginUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginUserCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterUserCommand}
 */
// @ts-ignore
export function createRegisterUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterUserCommand;
}
export interface CreateTaskCommand extends Parsable {
    /**
     * The attribute property
     */
    attribute?: number | null;
    /**
     * The daysOfWeek property
     */
    daysOfWeek?: number[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDate property
     */
    endDate?: DateOnly | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The repeatInterval property
     */
    repeatInterval?: number | null;
    /**
     * The repetitionType property
     */
    repetitionType?: number | null;
    /**
     * The startDate property
     */
    startDate?: DateOnly | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUserDetailsCommand}
 */
// @ts-ignore
export function createUpdateUserDetailsCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUserDetailsCommand;
}
/**
 * The deserialization information for the current model
 * @param ApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApiOperationResult(apiOperationResult: Partial<ApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { apiOperationResult.errors = n.getObjectValue<ApiOperationResult_errors>(createApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { apiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApiOperationResult_errors(apiOperationResult_errors: Partial<ApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ConfirmEmailCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfirmEmailCommand(confirmEmailCommand: Partial<ConfirmEmailCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "confirmationCode": n => { confirmEmailCommand.confirmationCode = n.getStringValue(); },
        "userId": n => { confirmEmailCommand.userId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateTaskCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateTaskCommand(createTaskCommand: Partial<CreateTaskCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attribute": n => { createTaskCommand.attribute = n.getNumberValue(); },
        "daysOfWeek": n => { createTaskCommand.daysOfWeek = n.getCollectionOfPrimitiveValues<number>(); },
        "description": n => { createTaskCommand.description = n.getStringValue(); },
        "endDate": n => { createTaskCommand.endDate = n.getDateOnlyValue(); },
        "exp": n => { createTaskCommand.exp = n.getNumberValue(); },
        "repeatInterval": n => { createTaskCommand.repeatInterval = n.getNumberValue(); },
        "repetitionType": n => { createTaskCommand.repetitionType = n.getNumberValue(); },
        "startDate": n => { createTaskCommand.startDate = n.getDateOnlyValue(); },
        "title": n => { createTaskCommand.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponse(loginResponse: Partial<LoginResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { loginResponse.expiresIn = n.getNumberValue(); },
        "refreshToken": n => { loginResponse.refreshToken = n.getStringValue(); },
        "tokenType": n => { loginResponse.tokenType = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponseApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponseApiOperationResult(loginResponseApiOperationResult: Partial<LoginResponseApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { loginResponseApiOperationResult.data = n.getObjectValue<LoginResponse>(createLoginResponseFromDiscriminatorValue); },
        "errors": n => { loginResponseApiOperationResult.errors = n.getObjectValue<LoginResponseApiOperationResult_errors>(createLoginResponseApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { loginResponseApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponseApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponseApiOperationResult_errors(loginResponseApiOperationResult_errors: Partial<LoginResponseApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param LoginUserCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginUserCommand(loginUserCommand: Partial<LoginUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginUserCommand.email = n.getStringValue(); },
        "password": n => { loginUserCommand.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterUserCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterUserCommand(registerUserCommand: Partial<RegisterUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerUserCommand.email = n.getStringValue(); },
        "password": n => { registerUserCommand.password = n.getStringValue(); },
        "username": n => { registerUserCommand.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateUserDetailsCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUserDetailsCommand(updateUserDetailsCommand: Partial<UpdateUserDetailsCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "username": n => { updateUserDetailsCommand.username = n.getStringValue(); },
    }
}
export interface LoginResponse extends Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The expiresIn property
     */
    expiresIn?: number | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
    /**
     * The tokenType property
     */
    tokenType?: string | null;
}
export interface LoginResponseApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data?: LoginResponse | null;
    /**
     * The errors property
     */
    errors?: LoginResponseApiOperationResult_errors | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
}
export interface LoginResponseApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface LoginUserCommand extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface RegisterUserCommand extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The username property
     */
    username?: string | null;
}
/**
 * Serializes information the current object
 * @param ApiOperationResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApiOperationResult(writer: SerializationWriter, apiOperationResult: Partial<ApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!apiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ApiOperationResult_errors>("errors", apiOperationResult.errors, serializeApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", apiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param ApiOperationResult_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApiOperationResult_errors(writer: SerializationWriter, apiOperationResult_errors: Partial<ApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!apiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(apiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param ConfirmEmailCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfirmEmailCommand(writer: SerializationWriter, confirmEmailCommand: Partial<ConfirmEmailCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!confirmEmailCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("confirmationCode", confirmEmailCommand.confirmationCode);
    writer.writeStringValue("userId", confirmEmailCommand.userId);
}
/**
 * Serializes information the current object
 * @param CreateTaskCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateTaskCommand(writer: SerializationWriter, createTaskCommand: Partial<CreateTaskCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createTaskCommand || isSerializingDerivedType) { return; }
    writer.writeNumberValue("attribute", createTaskCommand.attribute);
    writer.writeCollectionOfPrimitiveValues<number>("daysOfWeek", createTaskCommand.daysOfWeek);
    writer.writeStringValue("description", createTaskCommand.description);
    writer.writeDateOnlyValue("endDate", createTaskCommand.endDate);
    writer.writeNumberValue("exp", createTaskCommand.exp);
    writer.writeNumberValue("repeatInterval", createTaskCommand.repeatInterval);
    writer.writeNumberValue("repetitionType", createTaskCommand.repetitionType);
    writer.writeDateOnlyValue("startDate", createTaskCommand.startDate);
    writer.writeStringValue("title", createTaskCommand.title);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponse(writer: SerializationWriter, loginResponse: Partial<LoginResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", loginResponse.accessToken);
    writer.writeNumberValue("expiresIn", loginResponse.expiresIn);
    writer.writeStringValue("refreshToken", loginResponse.refreshToken);
    writer.writeStringValue("tokenType", loginResponse.tokenType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponseApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponseApiOperationResult(writer: SerializationWriter, loginResponseApiOperationResult: Partial<LoginResponseApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponseApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<LoginResponse>("data", loginResponseApiOperationResult.data, serializeLoginResponse);
    writer.writeObjectValue<LoginResponseApiOperationResult_errors>("errors", loginResponseApiOperationResult.errors, serializeLoginResponseApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", loginResponseApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponseApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponseApiOperationResult_errors(writer: SerializationWriter, loginResponseApiOperationResult_errors: Partial<LoginResponseApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponseApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(loginResponseApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginUserCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginUserCommand(writer: SerializationWriter, loginUserCommand: Partial<LoginUserCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginUserCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginUserCommand.email);
    writer.writeStringValue("password", loginUserCommand.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterUserCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterUserCommand(writer: SerializationWriter, registerUserCommand: Partial<RegisterUserCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerUserCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", registerUserCommand.email);
    writer.writeStringValue("password", registerUserCommand.password);
    writer.writeStringValue("username", registerUserCommand.username);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateUserDetailsCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUserDetailsCommand(writer: SerializationWriter, updateUserDetailsCommand: Partial<UpdateUserDetailsCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateUserDetailsCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("username", updateUserDetailsCommand.username);
}
export interface UpdateUserDetailsCommand extends Parsable {
    /**
     * The username property
     */
    username?: string | null;
}
/* tslint:enable */
/* eslint-enable */
