/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type DateOnly, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ApiOperationResult extends ApiError, Parsable {
    /**
     * The errors property
     */
    errors?: ApiOperationResult_errors | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
}
export interface ApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export type BaseAttribute = (typeof BaseAttributeObject)[keyof typeof BaseAttributeObject];
export interface ConfirmEmailCommand extends Parsable {
    /**
     * The confirmationCode property
     */
    confirmationCode?: string | null;
    /**
     * The userId property
     */
    userId?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApiOperationResult_errors}
 */
// @ts-ignore
export function createApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApiOperationResult}
 */
// @ts-ignore
export function createApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfirmEmailCommand}
 */
// @ts-ignore
export function createConfirmEmailCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfirmEmailCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateHabitCommand}
 */
// @ts-ignore
export function createCreateHabitCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateHabitCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateTaskCommand}
 */
// @ts-ignore
export function createCreateTaskCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateTaskCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DailySummaryDto}
 */
// @ts-ignore
export function createDailySummaryDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDailySummaryDto;
}
export interface CreateHabitCommand extends Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The targetValue property
     */
    targetValue?: number | null;
    /**
     * The unit property
     */
    unit?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HabitDto}
 */
// @ts-ignore
export function createHabitDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHabitDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LogHabitEntryCommand}
 */
// @ts-ignore
export function createLogHabitEntryCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLogHabitEntryCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponseApiOperationResult_errors}
 */
// @ts-ignore
export function createLoginResponseApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponseApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponseApiOperationResult}
 */
// @ts-ignore
export function createLoginResponseApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponseApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponse}
 */
// @ts-ignore
export function createLoginResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginUserCommand}
 */
// @ts-ignore
export function createLoginUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginUserCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterUserCommand}
 */
// @ts-ignore
export function createRegisterUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterUserCommand;
}
export interface CreateTaskCommand extends Parsable {
    /**
     * The attribute property
     */
    attribute?: BaseAttribute | null;
    /**
     * The daysOfWeek property
     */
    daysOfWeek?: DayOfWeek[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDate property
     */
    endDate?: DateOnly | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The repeatInterval property
     */
    repeatInterval?: number | null;
    /**
     * The repetitionType property
     */
    repetitionType?: TaskRepetitionType | null;
    /**
     * The startDate property
     */
    startDate?: DateOnly | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TaskItemDto}
 */
// @ts-ignore
export function createTaskItemDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTaskItemDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TodayTaskItemDto}
 */
// @ts-ignore
export function createTodayTaskItemDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTodayTaskItemDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateHabitCommand}
 */
// @ts-ignore
export function createUpdateHabitCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateHabitCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateTaskCommand}
 */
// @ts-ignore
export function createUpdateTaskCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateTaskCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUserDetailsCommand}
 */
// @ts-ignore
export function createUpdateUserDetailsCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUserDetailsCommand;
}
export interface DailySummaryDto extends Parsable {
    /**
     * The completedCount property
     */
    completedCount?: number | null;
    /**
     * The streak property
     */
    streak?: number | null;
    /**
     * The totalExpEarnedToday property
     */
    totalExpEarnedToday?: number | null;
}
export type DayOfWeek = (typeof DayOfWeekObject)[keyof typeof DayOfWeekObject];
/**
 * The deserialization information for the current model
 * @param ApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApiOperationResult(apiOperationResult: Partial<ApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { apiOperationResult.errors = n.getObjectValue<ApiOperationResult_errors>(createApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { apiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApiOperationResult_errors(apiOperationResult_errors: Partial<ApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ConfirmEmailCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfirmEmailCommand(confirmEmailCommand: Partial<ConfirmEmailCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "confirmationCode": n => { confirmEmailCommand.confirmationCode = n.getStringValue(); },
        "userId": n => { confirmEmailCommand.userId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateHabitCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateHabitCommand(createHabitCommand: Partial<CreateHabitCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createHabitCommand.name = n.getStringValue(); },
        "targetValue": n => { createHabitCommand.targetValue = n.getNumberValue(); },
        "unit": n => { createHabitCommand.unit = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateTaskCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateTaskCommand(createTaskCommand: Partial<CreateTaskCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attribute": n => { createTaskCommand.attribute = n.getEnumValue<BaseAttribute>(BaseAttributeObject); },
        "daysOfWeek": n => { createTaskCommand.daysOfWeek = n.getCollectionOfEnumValues<DayOfWeek>(DayOfWeekObject); },
        "description": n => { createTaskCommand.description = n.getStringValue(); },
        "endDate": n => { createTaskCommand.endDate = n.getDateOnlyValue(); },
        "exp": n => { createTaskCommand.exp = n.getNumberValue(); },
        "repeatInterval": n => { createTaskCommand.repeatInterval = n.getNumberValue(); },
        "repetitionType": n => { createTaskCommand.repetitionType = n.getEnumValue<TaskRepetitionType>(TaskRepetitionTypeObject); },
        "startDate": n => { createTaskCommand.startDate = n.getDateOnlyValue(); },
        "title": n => { createTaskCommand.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DailySummaryDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDailySummaryDto(dailySummaryDto: Partial<DailySummaryDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "completedCount": n => { dailySummaryDto.completedCount = n.getNumberValue(); },
        "streak": n => { dailySummaryDto.streak = n.getNumberValue(); },
        "totalExpEarnedToday": n => { dailySummaryDto.totalExpEarnedToday = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param HabitDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHabitDto(habitDto: Partial<HabitDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { habitDto.id = n.getGuidValue(); },
        "name": n => { habitDto.name = n.getStringValue(); },
        "targetValue": n => { habitDto.targetValue = n.getNumberValue(); },
        "todayValue": n => { habitDto.todayValue = n.getNumberValue(); },
        "unit": n => { habitDto.unit = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LogHabitEntryCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLogHabitEntryCommand(logHabitEntryCommand: Partial<LogHabitEntryCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "habitId": n => { logHabitEntryCommand.habitId = n.getGuidValue(); },
        "value": n => { logHabitEntryCommand.value = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponse(loginResponse: Partial<LoginResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { loginResponse.expiresIn = n.getNumberValue(); },
        "refreshToken": n => { loginResponse.refreshToken = n.getStringValue(); },
        "tokenType": n => { loginResponse.tokenType = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponseApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponseApiOperationResult(loginResponseApiOperationResult: Partial<LoginResponseApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { loginResponseApiOperationResult.data = n.getObjectValue<LoginResponse>(createLoginResponseFromDiscriminatorValue); },
        "errors": n => { loginResponseApiOperationResult.errors = n.getObjectValue<LoginResponseApiOperationResult_errors>(createLoginResponseApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { loginResponseApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponseApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponseApiOperationResult_errors(loginResponseApiOperationResult_errors: Partial<LoginResponseApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param LoginUserCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginUserCommand(loginUserCommand: Partial<LoginUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginUserCommand.email = n.getStringValue(); },
        "password": n => { loginUserCommand.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterUserCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterUserCommand(registerUserCommand: Partial<RegisterUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerUserCommand.email = n.getStringValue(); },
        "password": n => { registerUserCommand.password = n.getStringValue(); },
        "username": n => { registerUserCommand.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TaskItemDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTaskItemDto(taskItemDto: Partial<TaskItemDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "archivedAt": n => { taskItemDto.archivedAt = n.getDateValue(); },
        "attribute": n => { taskItemDto.attribute = n.getEnumValue<BaseAttribute>(BaseAttributeObject); },
        "createdAt": n => { taskItemDto.createdAt = n.getDateValue(); },
        "daysOfWeek": n => { taskItemDto.daysOfWeek = n.getCollectionOfEnumValues<DayOfWeek>(DayOfWeekObject); },
        "description": n => { taskItemDto.description = n.getStringValue(); },
        "endDate": n => { taskItemDto.endDate = n.getDateOnlyValue(); },
        "exp": n => { taskItemDto.exp = n.getNumberValue(); },
        "id": n => { taskItemDto.id = n.getGuidValue(); },
        "isArchived": n => { taskItemDto.isArchived = n.getBooleanValue(); },
        "isCompleted": n => { taskItemDto.isCompleted = n.getBooleanValue(); },
        "repeatInterval": n => { taskItemDto.repeatInterval = n.getNumberValue(); },
        "repetitionType": n => { taskItemDto.repetitionType = n.getEnumValue<TaskRepetitionType>(TaskRepetitionTypeObject); },
        "startDate": n => { taskItemDto.startDate = n.getDateOnlyValue(); },
        "title": n => { taskItemDto.title = n.getStringValue(); },
        "updatedAt": n => { taskItemDto.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TodayTaskItemDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTodayTaskItemDto(todayTaskItemDto: Partial<TodayTaskItemDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attribute": n => { todayTaskItemDto.attribute = n.getEnumValue<BaseAttribute>(BaseAttributeObject); },
        "daysOfWeek": n => { todayTaskItemDto.daysOfWeek = n.getCollectionOfEnumValues<DayOfWeek>(DayOfWeekObject); },
        "description": n => { todayTaskItemDto.description = n.getStringValue(); },
        "endDate": n => { todayTaskItemDto.endDate = n.getDateOnlyValue(); },
        "exp": n => { todayTaskItemDto.exp = n.getNumberValue(); },
        "id": n => { todayTaskItemDto.id = n.getGuidValue(); },
        "isCompleted": n => { todayTaskItemDto.isCompleted = n.getBooleanValue(); },
        "occurrenceId": n => { todayTaskItemDto.occurrenceId = n.getGuidValue(); },
        "occurrenceStatus": n => { todayTaskItemDto.occurrenceStatus = n.getEnumValue<TaskOccurrenceStatus>(TaskOccurrenceStatusObject); },
        "repeatInterval": n => { todayTaskItemDto.repeatInterval = n.getNumberValue(); },
        "repetitionType": n => { todayTaskItemDto.repetitionType = n.getEnumValue<TaskRepetitionType>(TaskRepetitionTypeObject); },
        "scheduledDate": n => { todayTaskItemDto.scheduledDate = n.getDateOnlyValue(); },
        "startDate": n => { todayTaskItemDto.startDate = n.getDateOnlyValue(); },
        "title": n => { todayTaskItemDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateHabitCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateHabitCommand(updateHabitCommand: Partial<UpdateHabitCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { updateHabitCommand.id = n.getGuidValue(); },
        "name": n => { updateHabitCommand.name = n.getStringValue(); },
        "targetValue": n => { updateHabitCommand.targetValue = n.getNumberValue(); },
        "unit": n => { updateHabitCommand.unit = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateTaskCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateTaskCommand(updateTaskCommand: Partial<UpdateTaskCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attribute": n => { updateTaskCommand.attribute = n.getEnumValue<BaseAttribute>(BaseAttributeObject); },
        "daysOfWeek": n => { updateTaskCommand.daysOfWeek = n.getCollectionOfEnumValues<DayOfWeek>(DayOfWeekObject); },
        "description": n => { updateTaskCommand.description = n.getStringValue(); },
        "endDate": n => { updateTaskCommand.endDate = n.getDateOnlyValue(); },
        "exp": n => { updateTaskCommand.exp = n.getNumberValue(); },
        "id": n => { updateTaskCommand.id = n.getGuidValue(); },
        "repeatInterval": n => { updateTaskCommand.repeatInterval = n.getNumberValue(); },
        "repetitionType": n => { updateTaskCommand.repetitionType = n.getEnumValue<TaskRepetitionType>(TaskRepetitionTypeObject); },
        "startDate": n => { updateTaskCommand.startDate = n.getDateOnlyValue(); },
        "title": n => { updateTaskCommand.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateUserDetailsCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUserDetailsCommand(updateUserDetailsCommand: Partial<UpdateUserDetailsCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "username": n => { updateUserDetailsCommand.username = n.getStringValue(); },
    }
}
export interface HabitDto extends Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The targetValue property
     */
    targetValue?: number | null;
    /**
     * The todayValue property
     */
    todayValue?: number | null;
    /**
     * The unit property
     */
    unit?: string | null;
}
export interface LogHabitEntryCommand extends Parsable {
    /**
     * The habitId property
     */
    habitId?: Guid | null;
    /**
     * The value property
     */
    value?: number | null;
}
export interface LoginResponse extends Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The expiresIn property
     */
    expiresIn?: number | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
    /**
     * The tokenType property
     */
    tokenType?: string | null;
}
export interface LoginResponseApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data?: LoginResponse | null;
    /**
     * The errors property
     */
    errors?: LoginResponseApiOperationResult_errors | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
}
export interface LoginResponseApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface LoginUserCommand extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface RegisterUserCommand extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The username property
     */
    username?: string | null;
}
/**
 * Serializes information the current object
 * @param ApiOperationResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApiOperationResult(writer: SerializationWriter, apiOperationResult: Partial<ApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!apiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ApiOperationResult_errors>("errors", apiOperationResult.errors, serializeApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", apiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param ApiOperationResult_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApiOperationResult_errors(writer: SerializationWriter, apiOperationResult_errors: Partial<ApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!apiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(apiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param ConfirmEmailCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfirmEmailCommand(writer: SerializationWriter, confirmEmailCommand: Partial<ConfirmEmailCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!confirmEmailCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("confirmationCode", confirmEmailCommand.confirmationCode);
    writer.writeStringValue("userId", confirmEmailCommand.userId);
}
/**
 * Serializes information the current object
 * @param CreateHabitCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateHabitCommand(writer: SerializationWriter, createHabitCommand: Partial<CreateHabitCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createHabitCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createHabitCommand.name);
    writer.writeNumberValue("targetValue", createHabitCommand.targetValue);
    writer.writeStringValue("unit", createHabitCommand.unit);
}
/**
 * Serializes information the current object
 * @param CreateTaskCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateTaskCommand(writer: SerializationWriter, createTaskCommand: Partial<CreateTaskCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createTaskCommand || isSerializingDerivedType) { return; }
    writer.writeEnumValue<BaseAttribute>("attribute", createTaskCommand.attribute);
    if(createTaskCommand.daysOfWeek)
    writer.writeCollectionOfEnumValues<DayOfWeek>("daysOfWeek", createTaskCommand.daysOfWeek);
    writer.writeStringValue("description", createTaskCommand.description);
    writer.writeDateOnlyValue("endDate", createTaskCommand.endDate);
    writer.writeNumberValue("exp", createTaskCommand.exp);
    writer.writeNumberValue("repeatInterval", createTaskCommand.repeatInterval);
    writer.writeEnumValue<TaskRepetitionType>("repetitionType", createTaskCommand.repetitionType);
    writer.writeDateOnlyValue("startDate", createTaskCommand.startDate);
    writer.writeStringValue("title", createTaskCommand.title);
}
/**
 * Serializes information the current object
 * @param DailySummaryDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDailySummaryDto(writer: SerializationWriter, dailySummaryDto: Partial<DailySummaryDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dailySummaryDto || isSerializingDerivedType) { return; }
    writer.writeNumberValue("completedCount", dailySummaryDto.completedCount);
    writer.writeNumberValue("streak", dailySummaryDto.streak);
    writer.writeNumberValue("totalExpEarnedToday", dailySummaryDto.totalExpEarnedToday);
}
/**
 * Serializes information the current object
 * @param HabitDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHabitDto(writer: SerializationWriter, habitDto: Partial<HabitDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!habitDto || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", habitDto.id);
    writer.writeStringValue("name", habitDto.name);
    writer.writeNumberValue("targetValue", habitDto.targetValue);
    writer.writeNumberValue("todayValue", habitDto.todayValue);
    writer.writeStringValue("unit", habitDto.unit);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LogHabitEntryCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLogHabitEntryCommand(writer: SerializationWriter, logHabitEntryCommand: Partial<LogHabitEntryCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!logHabitEntryCommand || isSerializingDerivedType) { return; }
    writer.writeGuidValue("habitId", logHabitEntryCommand.habitId);
    writer.writeNumberValue("value", logHabitEntryCommand.value);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponse(writer: SerializationWriter, loginResponse: Partial<LoginResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", loginResponse.accessToken);
    writer.writeNumberValue("expiresIn", loginResponse.expiresIn);
    writer.writeStringValue("refreshToken", loginResponse.refreshToken);
    writer.writeStringValue("tokenType", loginResponse.tokenType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponseApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponseApiOperationResult(writer: SerializationWriter, loginResponseApiOperationResult: Partial<LoginResponseApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponseApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<LoginResponse>("data", loginResponseApiOperationResult.data, serializeLoginResponse);
    writer.writeObjectValue<LoginResponseApiOperationResult_errors>("errors", loginResponseApiOperationResult.errors, serializeLoginResponseApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", loginResponseApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponseApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponseApiOperationResult_errors(writer: SerializationWriter, loginResponseApiOperationResult_errors: Partial<LoginResponseApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponseApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(loginResponseApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginUserCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginUserCommand(writer: SerializationWriter, loginUserCommand: Partial<LoginUserCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginUserCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginUserCommand.email);
    writer.writeStringValue("password", loginUserCommand.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterUserCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterUserCommand(writer: SerializationWriter, registerUserCommand: Partial<RegisterUserCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerUserCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", registerUserCommand.email);
    writer.writeStringValue("password", registerUserCommand.password);
    writer.writeStringValue("username", registerUserCommand.username);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TaskItemDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTaskItemDto(writer: SerializationWriter, taskItemDto: Partial<TaskItemDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!taskItemDto || isSerializingDerivedType) { return; }
    writer.writeDateValue("archivedAt", taskItemDto.archivedAt);
    writer.writeEnumValue<BaseAttribute>("attribute", taskItemDto.attribute);
    writer.writeDateValue("createdAt", taskItemDto.createdAt);
    if(taskItemDto.daysOfWeek)
    writer.writeCollectionOfEnumValues<DayOfWeek>("daysOfWeek", taskItemDto.daysOfWeek);
    writer.writeStringValue("description", taskItemDto.description);
    writer.writeDateOnlyValue("endDate", taskItemDto.endDate);
    writer.writeNumberValue("exp", taskItemDto.exp);
    writer.writeGuidValue("id", taskItemDto.id);
    writer.writeBooleanValue("isArchived", taskItemDto.isArchived);
    writer.writeBooleanValue("isCompleted", taskItemDto.isCompleted);
    writer.writeNumberValue("repeatInterval", taskItemDto.repeatInterval);
    writer.writeEnumValue<TaskRepetitionType>("repetitionType", taskItemDto.repetitionType);
    writer.writeDateOnlyValue("startDate", taskItemDto.startDate);
    writer.writeStringValue("title", taskItemDto.title);
    writer.writeDateValue("updatedAt", taskItemDto.updatedAt);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TodayTaskItemDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTodayTaskItemDto(writer: SerializationWriter, todayTaskItemDto: Partial<TodayTaskItemDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!todayTaskItemDto || isSerializingDerivedType) { return; }
    writer.writeEnumValue<BaseAttribute>("attribute", todayTaskItemDto.attribute);
    if(todayTaskItemDto.daysOfWeek)
    writer.writeCollectionOfEnumValues<DayOfWeek>("daysOfWeek", todayTaskItemDto.daysOfWeek);
    writer.writeStringValue("description", todayTaskItemDto.description);
    writer.writeDateOnlyValue("endDate", todayTaskItemDto.endDate);
    writer.writeNumberValue("exp", todayTaskItemDto.exp);
    writer.writeGuidValue("id", todayTaskItemDto.id);
    writer.writeBooleanValue("isCompleted", todayTaskItemDto.isCompleted);
    writer.writeGuidValue("occurrenceId", todayTaskItemDto.occurrenceId);
    writer.writeEnumValue<TaskOccurrenceStatus>("occurrenceStatus", todayTaskItemDto.occurrenceStatus);
    writer.writeNumberValue("repeatInterval", todayTaskItemDto.repeatInterval);
    writer.writeEnumValue<TaskRepetitionType>("repetitionType", todayTaskItemDto.repetitionType);
    writer.writeDateOnlyValue("scheduledDate", todayTaskItemDto.scheduledDate);
    writer.writeDateOnlyValue("startDate", todayTaskItemDto.startDate);
    writer.writeStringValue("title", todayTaskItemDto.title);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateHabitCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateHabitCommand(writer: SerializationWriter, updateHabitCommand: Partial<UpdateHabitCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateHabitCommand || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", updateHabitCommand.id);
    writer.writeStringValue("name", updateHabitCommand.name);
    writer.writeNumberValue("targetValue", updateHabitCommand.targetValue);
    writer.writeStringValue("unit", updateHabitCommand.unit);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateTaskCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateTaskCommand(writer: SerializationWriter, updateTaskCommand: Partial<UpdateTaskCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateTaskCommand || isSerializingDerivedType) { return; }
    writer.writeEnumValue<BaseAttribute>("attribute", updateTaskCommand.attribute);
    if(updateTaskCommand.daysOfWeek)
    writer.writeCollectionOfEnumValues<DayOfWeek>("daysOfWeek", updateTaskCommand.daysOfWeek);
    writer.writeStringValue("description", updateTaskCommand.description);
    writer.writeDateOnlyValue("endDate", updateTaskCommand.endDate);
    writer.writeNumberValue("exp", updateTaskCommand.exp);
    writer.writeGuidValue("id", updateTaskCommand.id);
    writer.writeNumberValue("repeatInterval", updateTaskCommand.repeatInterval);
    writer.writeEnumValue<TaskRepetitionType>("repetitionType", updateTaskCommand.repetitionType);
    writer.writeDateOnlyValue("startDate", updateTaskCommand.startDate);
    writer.writeStringValue("title", updateTaskCommand.title);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateUserDetailsCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUserDetailsCommand(writer: SerializationWriter, updateUserDetailsCommand: Partial<UpdateUserDetailsCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateUserDetailsCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("username", updateUserDetailsCommand.username);
}
export interface TaskItemDto extends Parsable {
    /**
     * The archivedAt property
     */
    archivedAt?: Date | null;
    /**
     * The attribute property
     */
    attribute?: BaseAttribute | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The daysOfWeek property
     */
    daysOfWeek?: DayOfWeek[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDate property
     */
    endDate?: DateOnly | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isArchived property
     */
    isArchived?: boolean | null;
    /**
     * The isCompleted property
     */
    isCompleted?: boolean | null;
    /**
     * The repeatInterval property
     */
    repeatInterval?: number | null;
    /**
     * The repetitionType property
     */
    repetitionType?: TaskRepetitionType | null;
    /**
     * The startDate property
     */
    startDate?: DateOnly | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export type TaskOccurrenceStatus = (typeof TaskOccurrenceStatusObject)[keyof typeof TaskOccurrenceStatusObject];
export type TaskRepetitionType = (typeof TaskRepetitionTypeObject)[keyof typeof TaskRepetitionTypeObject];
export interface TodayTaskItemDto extends Parsable {
    /**
     * The attribute property
     */
    attribute?: BaseAttribute | null;
    /**
     * The daysOfWeek property
     */
    daysOfWeek?: DayOfWeek[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDate property
     */
    endDate?: DateOnly | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isCompleted property
     */
    isCompleted?: boolean | null;
    /**
     * The occurrenceId property
     */
    occurrenceId?: Guid | null;
    /**
     * The occurrenceStatus property
     */
    occurrenceStatus?: TaskOccurrenceStatus | null;
    /**
     * The repeatInterval property
     */
    repeatInterval?: number | null;
    /**
     * The repetitionType property
     */
    repetitionType?: TaskRepetitionType | null;
    /**
     * The scheduledDate property
     */
    scheduledDate?: DateOnly | null;
    /**
     * The startDate property
     */
    startDate?: DateOnly | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface UpdateHabitCommand extends Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The targetValue property
     */
    targetValue?: number | null;
    /**
     * The unit property
     */
    unit?: string | null;
}
export interface UpdateTaskCommand extends Parsable {
    /**
     * The attribute property
     */
    attribute?: BaseAttribute | null;
    /**
     * The daysOfWeek property
     */
    daysOfWeek?: DayOfWeek[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDate property
     */
    endDate?: DateOnly | null;
    /**
     * The exp property
     */
    exp?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The repeatInterval property
     */
    repeatInterval?: number | null;
    /**
     * The repetitionType property
     */
    repetitionType?: TaskRepetitionType | null;
    /**
     * The startDate property
     */
    startDate?: DateOnly | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface UpdateUserDetailsCommand extends Parsable {
    /**
     * The username property
     */
    username?: string | null;
}
export const BaseAttributeObject = {
    Strength: "Strength",
    Knowledge: "Knowledge",
    Health: "Health",
    Charisma: "Charisma",
    Focus: "Focus",
    Creativity: "Creativity",
} as const;
export const DayOfWeekObject = {
    Sunday: "Sunday",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
} as const;
export const TaskOccurrenceStatusObject = {
    Pending: "Pending",
    Done: "Done",
    Missed: "Missed",
} as const;
export const TaskRepetitionTypeObject = {
    Once: "Once",
    Daily: "Daily",
    Weekly: "Weekly",
} as const;
/* tslint:enable */
/* eslint-enable */
