/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHabitDtoFromDiscriminatorValue, serializeCreateHabitCommand, type CreateHabitCommand, type HabitDto } from '../../models/index.js';
// @ts-ignore
import { HabitsItemRequestBuilderNavigationMetadata, HabitsItemRequestBuilderRequestsMetadata, type HabitsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/habits
 */
export interface HabitsRequestBuilder extends BaseRequestBuilder<HabitsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.habits.item collection
     * @param id Unique identifier of the item
     * @returns {HabitsItemRequestBuilder}
     */
     byId(id: Guid) : HabitsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HabitDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HabitDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: CreateHabitCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateHabitCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HabitsRequestBuilderUriTemplate = "{+baseurl}/api/habits";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HabitsRequestBuilderNavigationMetadata: Record<Exclude<keyof HabitsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: HabitsItemRequestBuilderRequestsMetadata,
        navigationMetadata: HabitsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const HabitsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: HabitsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createHabitDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: HabitsRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateHabitCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
