/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EquipRequestBuilderRequestsMetadata, type EquipRequestBuilder } from './equip/index.js';
// @ts-ignore
import { type UnequipRequestBuilder, UnequipRequestBuilderRequestsMetadata } from './unequip/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character/items/{userItemId}
 */
export interface WithUserItemItemRequestBuilder extends BaseRequestBuilder<WithUserItemItemRequestBuilder> {
    /**
     * The equip property
     */
    get equip(): EquipRequestBuilder;
    /**
     * The unequip property
     */
    get unequip(): UnequipRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemItemRequestBuilderUriTemplate = "{+baseurl}/api/character/items/{userItemId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithUserItemItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithUserItemItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    equip: {
        requestsMetadata: EquipRequestBuilderRequestsMetadata,
    },
    unequip: {
        requestsMetadata: UnequipRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
