/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  IdentityRequestBuilderNavigationMetadata,
  type IdentityRequestBuilder,
} from './identity/index.js';
// @ts-ignore
import { TasksRequestBuilderRequestsMetadata, type TasksRequestBuilder } from './tasks/index.js';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
  /**
   * The identity property
   */
  get identity(): IdentityRequestBuilder;
  /**
   * The tasks property
   */
  get tasks(): TasksRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = '{+baseurl}/api';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<
  Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  identity: {
    navigationMetadata: IdentityRequestBuilderNavigationMetadata,
  },
  tasks: {
    requestsMetadata: TasksRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
