/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTodayTaskItemDtoFromDiscriminatorValue, type TodayTaskItemDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tasks/today
 */
export interface TodayRequestBuilder extends BaseRequestBuilder<TodayRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TodayTaskItemDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TodayTaskItemDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TodayRequestBuilderUriTemplate = "{+baseurl}/api/tasks/today";
/**
 * Metadata for all the requests in the request builder.
 */
export const TodayRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TodayRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTodayTaskItemDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
