/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OccurrencesItemRequestBuilderNavigationMetadata, type OccurrencesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/occurrences
 */
export interface OccurrencesRequestBuilder extends BaseRequestBuilder<OccurrencesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.occurrences.item collection
     * @param id Unique identifier of the item
     * @returns {OccurrencesItemRequestBuilder}
     */
     byId(id: Guid) : OccurrencesItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OccurrencesRequestBuilderUriTemplate = "{+baseurl}/api/occurrences";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OccurrencesRequestBuilderNavigationMetadata: Record<Exclude<keyof OccurrencesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        navigationMetadata: OccurrencesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
