/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeaderboardDtoFromDiscriminatorValue, type LeaderboardDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type DateOnly, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/community/leaderboard
 */
export interface LeaderboardRequestBuilder extends BaseRequestBuilder<LeaderboardRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeaderboardDto>}
     */
     get(requestConfiguration?: RequestConfiguration<LeaderboardRequestBuilderGetQueryParameters> | undefined) : Promise<LeaderboardDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LeaderboardRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface LeaderboardRequestBuilderGetQueryParameters {
    top?: number;
    weekStart?: DateOnly;
}
/**
 * Uri template for the request builder.
 */
export const LeaderboardRequestBuilderUriTemplate = "{+baseurl}/api/community/leaderboard{?top*,weekStart*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const LeaderboardRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LeaderboardRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createLeaderboardDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
