/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createContributionGridDtoFromDiscriminatorValue, type ContributionGridDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tasks/contribution-grid
 */
export interface ContributionGridRequestBuilder extends BaseRequestBuilder<ContributionGridRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ContributionGridDto>}
     */
     get(requestConfiguration?: RequestConfiguration<ContributionGridRequestBuilderGetQueryParameters> | undefined) : Promise<ContributionGridDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ContributionGridRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface ContributionGridRequestBuilderGetQueryParameters {
    year?: number;
}
/**
 * Uri template for the request builder.
 */
export const ContributionGridRequestBuilderUriTemplate = "{+baseurl}/api/tasks/contribution-grid{?year*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ContributionGridRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ContributionGridRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createContributionGridDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
