/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDayActivityDtoFromDiscriminatorValue, type DayActivityDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type DateOnly, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tasks/day-activity
 */
export interface DayActivityRequestBuilder extends BaseRequestBuilder<DayActivityRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DayActivityDto>}
     */
     get(requestConfiguration?: RequestConfiguration<DayActivityRequestBuilderGetQueryParameters> | undefined) : Promise<DayActivityDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DayActivityRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface DayActivityRequestBuilderGetQueryParameters {
    date?: DateOnly;
}
/**
 * Uri template for the request builder.
 */
export const DayActivityRequestBuilderUriTemplate = "{+baseurl}/api/tasks/day-activity{?date*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DayActivityRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DayActivityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDayActivityDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
