/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEquippedItemDtoFromDiscriminatorValue, type EquippedItemDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character/equipped-items
 */
export interface EquippedItemsRequestBuilder extends BaseRequestBuilder<EquippedItemsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EquippedItemDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EquippedItemDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EquippedItemsRequestBuilderUriTemplate = "{+baseurl}/api/character/equipped-items";
/**
 * Metadata for all the requests in the request builder.
 */
export const EquippedItemsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EquippedItemsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createEquippedItemDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
