/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWeeklyActivityDtoFromDiscriminatorValue, type WeeklyActivityDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type DateOnly, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/analytics/weekly-activity
 */
export interface WeeklyActivityRequestBuilder extends BaseRequestBuilder<WeeklyActivityRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WeeklyActivityDto>}
     */
     get(requestConfiguration?: RequestConfiguration<WeeklyActivityRequestBuilderGetQueryParameters> | undefined) : Promise<WeeklyActivityDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WeeklyActivityRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface WeeklyActivityRequestBuilderGetQueryParameters {
    weekStart?: DateOnly;
}
/**
 * Uri template for the request builder.
 */
export const WeeklyActivityRequestBuilderUriTemplate = "{+baseurl}/api/analytics/weekly-activity{?weekStart*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WeeklyActivityRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WeeklyActivityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createWeeklyActivityDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
