/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskItemDtoFromDiscriminatorValue, serializeCreateTaskCommand, type CreateTaskCommand, type TaskItemDto } from '../../models/index.js';
// @ts-ignore
import { DailySummaryRequestBuilderRequestsMetadata, type DailySummaryRequestBuilder } from './dailySummary/index.js';
// @ts-ignore
import { TasksItemRequestBuilderRequestsMetadata, type TasksItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { TodayRequestBuilderRequestsMetadata, type TodayRequestBuilder } from './today/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tasks
 */
export interface TasksRequestBuilder extends BaseRequestBuilder<TasksRequestBuilder> {
    /**
     * The dailySummary property
     */
    get dailySummary(): DailySummaryRequestBuilder;
    /**
     * The today property
     */
    get today(): TodayRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.tasks.item collection
     * @param id Unique identifier of the item
     * @returns {TasksItemRequestBuilder}
     */
     byId(id: Guid) : TasksItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskItemDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskItemDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: CreateTaskCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateTaskCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TasksRequestBuilderUriTemplate = "{+baseurl}/api/tasks";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TasksRequestBuilderNavigationMetadata: Record<Exclude<keyof TasksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TasksItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    dailySummary: {
        requestsMetadata: DailySummaryRequestBuilderRequestsMetadata,
    },
    today: {
        requestsMetadata: TodayRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TasksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TasksRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskItemDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: TasksRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateTaskCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
