/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  serializeUpdateUserDetailsCommand,
  type UpdateUserDetailsCommand,
} from '../../../models/index.js';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/identity/user
 */
export interface UserRequestBuilder extends BaseRequestBuilder<UserRequestBuilder> {
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<ArrayBuffer>}
   */
  patch(
    body: UpdateUserDetailsCommand,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): Promise<ArrayBuffer | undefined>;
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPatchRequestInformation(
    body: UpdateUserDetailsCommand,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UserRequestBuilderUriTemplate = '{+baseurl}/api/identity/user';
/**
 * Metadata for all the requests in the request builder.
 */
export const UserRequestBuilderRequestsMetadata: RequestsMetadata = {
  patch: {
    uriTemplate: UserRequestBuilderUriTemplate,
    adapterMethodName: 'sendPrimitive',
    responseBodyFactory: 'ArrayBuffer',
    requestBodyContentType: 'application/json',
    requestBodySerializer: serializeUpdateUserDetailsCommand,
    requestInformationContentSetMethod: 'setContentFromParsable',
  },
};
/* tslint:enable */
/* eslint-enable */
