/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiOperationResultFromDiscriminatorValue, serializeApiOperationResult, serializeConfirmEmailCommand, type ApiOperationResult, type ConfirmEmailCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/identity/confirmEmail
 */
export interface ConfirmEmailRequestBuilder extends BaseRequestBuilder<ConfirmEmailRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiOperationResult>}
     * @throws {ApiOperationResult} error when the service returns a 400 status code
     */
     post(body: ConfirmEmailCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ConfirmEmailCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConfirmEmailRequestBuilderUriTemplate = "{+baseurl}/api/identity/confirmEmail";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConfirmEmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConfirmEmailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createApiOperationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeConfirmEmailCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
