/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeConfirmEmailCommand, type ConfirmEmailCommand } from '../../../models/index.js';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/identity/confirmEmail
 */
export interface ConfirmEmailRequestBuilder extends BaseRequestBuilder<ConfirmEmailRequestBuilder> {
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<ArrayBuffer>}
   */
  post(
    body: ConfirmEmailCommand,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): Promise<ArrayBuffer | undefined>;
  /**
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPostRequestInformation(
    body: ConfirmEmailCommand,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConfirmEmailRequestBuilderUriTemplate = '{+baseurl}/api/identity/confirmEmail';
/**
 * Metadata for all the requests in the request builder.
 */
export const ConfirmEmailRequestBuilderRequestsMetadata: RequestsMetadata = {
  post: {
    uriTemplate: ConfirmEmailRequestBuilderUriTemplate,
    adapterMethodName: 'sendPrimitive',
    responseBodyFactory: 'ArrayBuffer',
    requestBodyContentType: 'application/json',
    requestBodySerializer: serializeConfirmEmailCommand,
    requestInformationContentSetMethod: 'setContentFromParsable',
  },
};
/* tslint:enable */
/* eslint-enable */
