/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithUserItemItemRequestBuilder, WithUserItemItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character/items
 */
export interface ItemsRequestBuilder extends BaseRequestBuilder<ItemsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.character.items.item collection
     * @param userItemId Unique identifier of the item
     * @returns {WithUserItemItemRequestBuilder}
     */
     byUserItemId(userItemId: Guid) : WithUserItemItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ItemsRequestBuilderUriTemplate = "{+baseurl}/api/character/items";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemsRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserItemId: {
        navigationMetadata: WithUserItemItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["userItemId"],
    },
};
/* tslint:enable */
/* eslint-enable */
