/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AchievementsRequestBuilderRequestsMetadata, type AchievementsRequestBuilder } from './achievements/index.js';
// @ts-ignore
import { LifeBalanceRequestBuilderRequestsMetadata, type LifeBalanceRequestBuilder } from './lifeBalance/index.js';
// @ts-ignore
import { OverviewRequestBuilderRequestsMetadata, type OverviewRequestBuilder } from './overview/index.js';
// @ts-ignore
import { StatGrowthRequestBuilderRequestsMetadata, type StatGrowthRequestBuilder } from './statGrowth/index.js';
// @ts-ignore
import { type WeeklyActivityRequestBuilder, WeeklyActivityRequestBuilderRequestsMetadata } from './weeklyActivity/index.js';
// @ts-ignore
import { type XpPerWeekRequestBuilder, XpPerWeekRequestBuilderRequestsMetadata } from './xpPerWeek/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/analytics
 */
export interface AnalyticsRequestBuilder extends BaseRequestBuilder<AnalyticsRequestBuilder> {
    /**
     * The achievements property
     */
    get achievements(): AchievementsRequestBuilder;
    /**
     * The lifeBalance property
     */
    get lifeBalance(): LifeBalanceRequestBuilder;
    /**
     * The overview property
     */
    get overview(): OverviewRequestBuilder;
    /**
     * The statGrowth property
     */
    get statGrowth(): StatGrowthRequestBuilder;
    /**
     * The weeklyActivity property
     */
    get weeklyActivity(): WeeklyActivityRequestBuilder;
    /**
     * The xpPerWeek property
     */
    get xpPerWeek(): XpPerWeekRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AnalyticsRequestBuilderUriTemplate = "{+baseurl}/api/analytics";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnalyticsRequestBuilderNavigationMetadata: Record<Exclude<keyof AnalyticsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    achievements: {
        requestsMetadata: AchievementsRequestBuilderRequestsMetadata,
    },
    lifeBalance: {
        requestsMetadata: LifeBalanceRequestBuilderRequestsMetadata,
    },
    overview: {
        requestsMetadata: OverviewRequestBuilderRequestsMetadata,
    },
    statGrowth: {
        requestsMetadata: StatGrowthRequestBuilderRequestsMetadata,
    },
    weeklyActivity: {
        requestsMetadata: WeeklyActivityRequestBuilderRequestsMetadata,
    },
    xpPerWeek: {
        requestsMetadata: XpPerWeekRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
