/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LeaderboardRequestBuilderRequestsMetadata, type LeaderboardRequestBuilder } from './leaderboard/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/community
 */
export interface CommunityRequestBuilder extends BaseRequestBuilder<CommunityRequestBuilder> {
    /**
     * The leaderboard property
     */
    get leaderboard(): LeaderboardRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CommunityRequestBuilderUriTemplate = "{+baseurl}/api/community";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CommunityRequestBuilderNavigationMetadata: Record<Exclude<keyof CommunityRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    leaderboard: {
        requestsMetadata: LeaderboardRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
