/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createStatGrowthDtoFromDiscriminatorValue, type StatGrowthDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/analytics/stat-growth
 */
export interface StatGrowthRequestBuilder extends BaseRequestBuilder<StatGrowthRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StatGrowthDto>}
     */
     get(requestConfiguration?: RequestConfiguration<StatGrowthRequestBuilderGetQueryParameters> | undefined) : Promise<StatGrowthDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StatGrowthRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface StatGrowthRequestBuilderGetQueryParameters {
    weeks?: number;
}
/**
 * Uri template for the request builder.
 */
export const StatGrowthRequestBuilderUriTemplate = "{+baseurl}/api/analytics/stat-growth{?weeks*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatGrowthRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatGrowthRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createStatGrowthDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
