// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfGrind.Infrastructure.Persistence;

#nullable disable

namespace SelfGrind.Infrastructure.Migrations
{
    [DbContext(typeof(SelfGrindDbContext))]
    partial class SelfGrindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.EvolutionTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NextEvolutionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("EvolutionTiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Emoji = "🌱",
                            MaxLevel = 10,
                            MinLevel = 1,
                            Name = "Novice",
                            NextEvolutionLabel = "Level 11: Apprentice",
                            Order = 1,
                            StageName = "Novice Adventurer"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Emoji = "📖",
                            MaxLevel = 20,
                            MinLevel = 11,
                            Name = "Apprentice",
                            NextEvolutionLabel = "Level 21: Adept",
                            Order = 2,
                            StageName = "Apprentice"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Emoji = "⚡",
                            MaxLevel = 30,
                            MinLevel = 21,
                            Name = "Adept",
                            NextEvolutionLabel = "Level 31: Expert",
                            Order = 3,
                            StageName = "Adept"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Emoji = "🔥",
                            MaxLevel = 40,
                            MinLevel = 31,
                            Name = "Expert",
                            NextEvolutionLabel = "Level 41: Master",
                            Order = 4,
                            StageName = "Elite Warrior"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Emoji = "👑",
                            MaxLevel = 50,
                            MinLevel = 41,
                            Name = "Master",
                            Order = 5,
                            StageName = "Legendary Champion"
                        });
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.HabitEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Bonus = "+10% Energy",
                            Emoji = "🧪",
                            Name = "Health Potion",
                            Rarity = "Common",
                            Type = "Consumable",
                            UnlockLevel = 1,
                            Variant = "Success"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Bonus = "+15 Knowledge XP",
                            Emoji = "📜",
                            Name = "Wisdom Scroll",
                            Rarity = "Uncommon",
                            Type = "Artifact",
                            UnlockLevel = 1,
                            Variant = "Info"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Bonus = "+25 Focus XP",
                            Emoji = "📿",
                            Name = "Focus Amulet",
                            Rarity = "Rare",
                            Type = "Artifact",
                            UnlockLevel = 3,
                            Variant = "Violet"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            Bonus = "+20% Strength",
                            Emoji = "💎",
                            Name = "Power Band",
                            Rarity = "Epic",
                            Type = "Accessory",
                            UnlockLevel = 5,
                            Variant = "Error"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            Bonus = "+20 Strength",
                            Emoji = "🧤",
                            Name = "Power Gauntlets",
                            Rarity = "Epic",
                            Type = "Gloves",
                            UnlockLevel = 5,
                            Variant = "Error"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            Bonus = "+30 Vitality",
                            Emoji = "💚",
                            Name = "Life Amulet",
                            Rarity = "Rare",
                            Type = "Artifact",
                            UnlockLevel = 4,
                            Variant = "Success"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            Bonus = "+50% XP Gain",
                            Emoji = "⭐",
                            Name = "XP Booster",
                            Rarity = "Legendary",
                            Type = "Boost",
                            UnlockLevel = 10,
                            Variant = "Warning"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            Bonus = "+22 Energy",
                            Emoji = "⚡",
                            Name = "Energy Crystal",
                            Rarity = "Uncommon",
                            Type = "Consumable",
                            UnlockLevel = 2,
                            Variant = "Warning"
                        });
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RequiredAttributeLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Attribute", "Order")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0001-000000000001"),
                            Attribute = "Strength",
                            Description = "Reach Strength level 1",
                            Emoji = "⚔️",
                            Name = "Warrior I",
                            Order = 1,
                            RequiredAttributeLevel = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0001-000000000002"),
                            Attribute = "Strength",
                            Description = "Reach Strength level 5",
                            Emoji = "🗡️",
                            Name = "Warrior II",
                            Order = 2,
                            RequiredAttributeLevel = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0001-000000000003"),
                            Attribute = "Strength",
                            Description = "Reach Strength level 10",
                            Emoji = "🛡️",
                            Name = "Warrior III",
                            Order = 3,
                            RequiredAttributeLevel = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0001-000000000004"),
                            Attribute = "Strength",
                            Description = "Reach Strength level 20",
                            Emoji = "💥",
                            Name = "Titan",
                            Order = 4,
                            RequiredAttributeLevel = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0002-000000000001"),
                            Attribute = "Knowledge",
                            Description = "Reach Knowledge level 1",
                            Emoji = "📖",
                            Name = "Scholar I",
                            Order = 1,
                            RequiredAttributeLevel = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0002-000000000002"),
                            Attribute = "Knowledge",
                            Description = "Reach Knowledge level 5",
                            Emoji = "📚",
                            Name = "Scholar II",
                            Order = 2,
                            RequiredAttributeLevel = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0002-000000000003"),
                            Attribute = "Knowledge",
                            Description = "Reach Knowledge level 10",
                            Emoji = "🎓",
                            Name = "Scholar III",
                            Order = 3,
                            RequiredAttributeLevel = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0002-000000000004"),
                            Attribute = "Knowledge",
                            Description = "Reach Knowledge level 20",
                            Emoji = "🧙",
                            Name = "Sage",
                            Order = 4,
                            RequiredAttributeLevel = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0003-000000000001"),
                            Attribute = "Focus",
                            Description = "Reach Focus level 1",
                            Emoji = "🧘",
                            Name = "Monk I",
                            Order = 1,
                            RequiredAttributeLevel = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0003-000000000002"),
                            Attribute = "Focus",
                            Description = "Reach Focus level 5",
                            Emoji = "🌿",
                            Name = "Monk II",
                            Order = 2,
                            RequiredAttributeLevel = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0003-000000000003"),
                            Attribute = "Focus",
                            Description = "Reach Focus level 10",
                            Emoji = "☯️",
                            Name = "Monk III",
                            Order = 3,
                            RequiredAttributeLevel = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0003-000000000004"),
                            Attribute = "Focus",
                            Description = "Reach Focus level 20",
                            Emoji = "✨",
                            Name = "Zen Master",
                            Order = 4,
                            RequiredAttributeLevel = 20
                        });
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Attribute")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskOccurrences");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("DaysOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RepeatInterval")
                        .HasColumnType("int");

                    b.Property<int>("RepetitionType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.ToTable("TaskSchedules");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredExp")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.UserItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.UserStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attribute")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("RequiredExp")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SelfGrind.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.Habit", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.HabitEntry", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.Habit", "Habit")
                        .WithMany("HabitEntries")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", "User")
                        .WithMany("TaskItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskOccurrence", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Occurrences")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskSchedule", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.TaskItem", "TaskItem")
                        .WithOne("Schedule")
                        .HasForeignKey("SelfGrind.Domain.Entities.TaskSchedule", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.UserItem", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SelfGrind.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.UserStat", b =>
                {
                    b.HasOne("SelfGrind.Domain.Entities.User", "User")
                        .WithMany("Stats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.Habit", b =>
                {
                    b.Navigation("HabitEntries");
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("SelfGrind.Domain.Entities.User", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("Stats");

                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
