/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeUpdateHabitCommand, type UpdateHabitCommand } from '../../../models/index.js';
// @ts-ignore
import { EntriesRequestBuilderRequestsMetadata, type EntriesRequestBuilder } from './entries/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/habits/{id}
 */
export interface HabitsItemRequestBuilder extends BaseRequestBuilder<HabitsItemRequestBuilder> {
    /**
     * The entries property
     */
    get entries(): EntriesRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     put(body: UpdateHabitCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateHabitCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HabitsItemRequestBuilderUriTemplate = "{+baseurl}/api/habits/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HabitsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof HabitsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    entries: {
        requestsMetadata: EntriesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const HabitsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: HabitsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    put: {
        uriTemplate: HabitsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateHabitCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
