/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSkillCategoryDtoFromDiscriminatorValue, type ProblemDetails, type SkillCategoryDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character/skill-trees
 */
export interface SkillTreesRequestBuilder extends BaseRequestBuilder<SkillTreesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SkillCategoryDto[]>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SkillCategoryDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SkillTreesRequestBuilderUriTemplate = "{+baseurl}/api/character/skill-trees";
/**
 * Metadata for all the requests in the request builder.
 */
export const SkillTreesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SkillTreesRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSkillCategoryDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
