/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EquippedItemsRequestBuilderRequestsMetadata, type EquippedItemsRequestBuilder } from './equippedItems/index.js';
// @ts-ignore
import { EvolutionTiersRequestBuilderRequestsMetadata, type EvolutionTiersRequestBuilder } from './evolutionTiers/index.js';
// @ts-ignore
import { HeroRequestBuilderRequestsMetadata, type HeroRequestBuilder } from './hero/index.js';
// @ts-ignore
import { InventoryRequestBuilderRequestsMetadata, type InventoryRequestBuilder } from './inventory/index.js';
// @ts-ignore
import { ItemsRequestBuilderNavigationMetadata, type ItemsRequestBuilder } from './items/index.js';
// @ts-ignore
import { SkillTreesRequestBuilderRequestsMetadata, type SkillTreesRequestBuilder } from './skillTrees/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character
 */
export interface CharacterRequestBuilder extends BaseRequestBuilder<CharacterRequestBuilder> {
    /**
     * The equippedItems property
     */
    get equippedItems(): EquippedItemsRequestBuilder;
    /**
     * The evolutionTiers property
     */
    get evolutionTiers(): EvolutionTiersRequestBuilder;
    /**
     * The hero property
     */
    get hero(): HeroRequestBuilder;
    /**
     * The inventory property
     */
    get inventory(): InventoryRequestBuilder;
    /**
     * The items property
     */
    get items(): ItemsRequestBuilder;
    /**
     * The skillTrees property
     */
    get skillTrees(): SkillTreesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CharacterRequestBuilderUriTemplate = "{+baseurl}/api/character";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CharacterRequestBuilderNavigationMetadata: Record<Exclude<keyof CharacterRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    equippedItems: {
        requestsMetadata: EquippedItemsRequestBuilderRequestsMetadata,
    },
    evolutionTiers: {
        requestsMetadata: EvolutionTiersRequestBuilderRequestsMetadata,
    },
    hero: {
        requestsMetadata: HeroRequestBuilderRequestsMetadata,
    },
    inventory: {
        requestsMetadata: InventoryRequestBuilderRequestsMetadata,
    },
    items: {
        navigationMetadata: ItemsRequestBuilderNavigationMetadata,
    },
    skillTrees: {
        requestsMetadata: SkillTreesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
