/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDailySummaryDtoFromDiscriminatorValue, type DailySummaryDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tasks/daily-summary
 */
export interface DailySummaryRequestBuilder extends BaseRequestBuilder<DailySummaryRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DailySummaryDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DailySummaryDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DailySummaryRequestBuilderUriTemplate = "{+baseurl}/api/tasks/daily-summary";
/**
 * Metadata for all the requests in the request builder.
 */
export const DailySummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DailySummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDailySummaryDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
