/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEvolutionTierDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type EvolutionTierDto, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/character/evolution-tiers
 */
export interface EvolutionTiersRequestBuilder extends BaseRequestBuilder<EvolutionTiersRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EvolutionTierDto[]>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EvolutionTierDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EvolutionTiersRequestBuilderUriTemplate = "{+baseurl}/api/character/evolution-tiers";
/**
 * Metadata for all the requests in the request builder.
 */
export const EvolutionTiersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EvolutionTiersRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createEvolutionTierDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
